language: python
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: 
            - choco install python
      env: PATH=/C/Users/vcmb1:/C/Users/vcmb1/Scripts:$PATH
install:
  - pip install -r requirements.txt
script: python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: "API_KEY"
    app: bikiservices

