# Generated by Django 2.2 on 2019-04-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceType', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('price', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('adress', models.CharField(max_length=30)),
            ],
        ),
    ]
