# Generated by Django 2.2 on 2019-05-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='serviceType',
            new_name='type',
        ),
    ]
